### ISSUE TITLE
Can't get beyond "None of the allowed keys is able to decrypt the content" message

### ISSUE THREAD

**Issue by kerlerm** [open-keychain/open-keychain#1277]
When using k9 to decrypt an email a message saying "None of the allowed keys is able to decrypt the content. Please select the allowed keys" is shown. However, I can't get past this point, because pressing "save" doesn't do anything despite my key being shown below this message.

This only happens when I try to decrypt a message which was sent to someone else and is also encrypted to myself.

Worked before 3.2.x version. Seems to be a regression.
Is not solved by latest update  3.2.1 as proposed by Google PlayStore reply.

Logcat doesn't show anything interesting. I'll attach it anyhow.

**Comment by kerlerm** [comment]
```
I/ActivityManager( 1227): START u0 {dat=content://org.sufficientlysecure.keychain.provider/api_apps/com.fsck.k9 cmp=org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity (has extras)} from pid -1
I/Timeline( 7615): Timeline: Activity_idle id: android.os.BinderProxy@428fdff8 time:126050268
I/ActivityManager( 1227): Process org.cyanogenmod.bugreport (pid 14545) has died.
W/SurfaceFlinger(  943): couldn't log to binary event log: overflow.
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ActivityManager( 1227): Process com.android.vending (pid 14580) has died.
I/ActivityManager( 1227): Displayed org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity: +502ms
W/IInputConnectionWrapper( 7615): showStatusIcon on inactive InputConnection
I/Timeline(12993): Timeline: Activity_idle id: android.os.BinderProxy@424e2c28 time:126050795
I/Timeline( 1227): Timeline: Activity_windows_visible id: ActivityRecord{42504340 u0 org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity t169} time:126051095
W/ManagedEGLContext( 7615): doTerminate failed: EGL count is 2 but managed count is 1
I/Timeline( 7615): Timeline: Activity_idle id: android.os.BinderProxy@428fdff8 time:126058126
I/ActivityManager( 1227): START u0 {dat=content://org.sufficientlysecure.keychain.provider/api_apps/com.fsck.k9 cmp=org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity (has extras)} from pid -1
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ActivityManager( 1227): Displayed org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity: +255ms
W/IInputConnectionWrapper( 7615): showStatusIcon on inactive InputConnection
W/SurfaceFlinger(  943): couldn't log to binary event log: overflow.
I/Timeline(12993): Timeline: Activity_idle id: android.os.BinderProxy@42a8ac48 time:126058589
I/Timeline( 1227): Timeline: Activity_windows_visible id: ActivityRecord{42519a70 u0 org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity t169} time:126058731
W/ManagedEGLContext( 7615): doTerminate failed: EGL count is 2 but managed count is 1
I/ActivityManager( 1227): START u0 {dat=content://org.sufficientlysecure.keychain.provider/api_apps/com.fsck.k9 cmp=org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity (has extras)} from pid -1
I/Timeline( 7615): Timeline: Activity_idle id: android.os.BinderProxy@428fdff8 time:126062064
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
W/SurfaceFlinger(  943): couldn't log to binary event log: overflow.
I/ActivityManager( 1227): Displayed org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity: +356ms
W/IInputConnectionWrapper( 7615): showStatusIcon on inactive InputConnection
I/Timeline(12993): Timeline: Activity_idle id: android.os.BinderProxy@42596260 time:126062485
I/Timeline( 1227): Timeline: Activity_windows_visible id: ActivityRecord{425ef310 u0 org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity t169} time:126062752
W/ManagedEGLContext( 7615): doTerminate failed: EGL count is 2 but managed count is 1
I/ActivityManager( 1227): START u0 {dat=content://org.sufficientlysecure.keychain.provider/api_apps/com.fsck.k9 cmp=org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity (has extras)} from pid -1
I/Timeline( 7615): Timeline: Activity_idle id: android.os.BinderProxy@428fdff8 time:126064826
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ViewUtils(12993): app:theme is now deprecated. Please move to using android:theme instead.
I/ActivityManager( 1227): Displayed org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity: +199ms
W/IInputConnectionWrapper( 7615): showStatusIcon on inactive InputConnection
I/Timeline(12993): Timeline: Activity_idle id: android.os.BinderProxy@4295c728 time:126065124
W/SurfaceFlinger(  943): couldn't log to binary event log: overflow.
I/Timeline( 1227): Timeline: Activity_windows_visible id: ActivityRecord{42739060 u0 org.sufficientlysecure.keychain/.remote.ui.SelectAllowedKeysActivity t169} time:126065362
W/ManagedEGLContext( 7615): doTerminate failed: EGL count is 2 but managed count is 1
```

**Comment by Valodim** [comment]
I would've thought this is the same issue as #1268, but that one should have been fixed in 3.2.1. Hmmm.

**Comment by dschuermann** [comment]
Will look into it

**Comment by brendes** [comment]
I'm getting the same issue when trying to access individual password entries in [Password Store](https://github.com/zeapo/Android-Password-Store), using OpenKeychain 3.2.1 from the F-Droid repo.

OpenKeychain states "None of the allowed keys is able to decrypt the content. Please select the allowed keys." My key appears below this message, with the checkbox checked. I click save, and am presented with the same dialog.

**Comment by brendes** [comment]
Just wanted to update, getting the same issue using OpenKeychain 3.2.2.

**Comment by Kangou** [comment]
Same for me, I can't access to password from Password Store when it was stored from my desktop (It work well for password stored from the phone). When I try to decrypt a file from the drawer menu "Crypt/uncrypt", I can only see the file encrypted from the phone, the files encrypted with the same key from my desktop or by another person are not displayed. If I try to decrypt those files from the phone file explorer, open-keychain open but do nothing when I hit the "decrypt" button.

**Comment by Valodim** [comment]
one of the problems here was that the "allowed keys" dialog is always shown if no key was found to decrypt data with, even if no key which could decrypt the data exists.

I fixed the latter problem in a8e95f676e580cfbab030aa0f58167a41149d00f.

**Comment by Kangou** [comment]
Sorry I was encrypting on the desktop with a second key not present on the phone, so the only bug I have is the one fixed by @Valodim.

**Comment by Valodim** [comment]
@brendes @kerlerm  was your problem also related to the fix above? or is this problem still present for you?

**Comment by kerlerm** [comment]
The problem persists for me even with 3.2.2 installed. As stated above, this only happens when I try to decrypt a message which was sent to someone else and is also encrypted to myself.
How can I provide debug output for you?

**Comment by dschuermann** [comment]
Let's wait for the upcoming bugfix release 3.2.3, and then we re-open this issue if you still experience problems.

**Comment by kerlerm** [comment]
3.2.3 fixed it. Thanks a lot.

**Comment by brendes** [comment]
Problem is fixed in 3.2.3. Thank you!
