### ISSUE TITLE
Unable to confirm keys.

### ISSUE THREAD

**Issue by pingu8007** [open-keychain/open-keychain#1388]
Is there anybody can confirm a key by fpr? I can't since I upgrade to 3.3 from Play Store.
Neither yubikey nor normal key pair can make confirmation successfully, both stuck at "building key…..."

Make confirmation by QR code didn't tried.

**Comment by dschuermann** [comment]
Confirmed. We will investigate.

**Comment by adithyaphilip** [comment]
Fixed in https://github.com/open-keychain/open-keychain/commit/5f170e5819a5b20cd22675f8848b60707f41c387 with operation migration.

**Comment by dschuermann** [comment]
I am still not able to confirm keys with a build from current master. Currently no dialog comes up. OpenKeychain freezes.

**Comment by adithyaphilip** [comment]
Sorry, looks like I messed up while rebasing. I've fixed it with https://github.com/open-keychain/open-keychain/pull/1396.

**Comment by dschuermann** [comment]
thanks, works now

**Comment by rafaelazvdo** [comment]
> Добрый день, как можно подтвердить старый ключ , не могу его активировать после переустановки системы андроид .

If you had not backed up your key pair before resetting your device, unfortunately you have lost your key forever and will no longer be able to restore it.


Если вы не создали резервную копию своей пары ключей перед перезагрузкой устройства, к сожалению, вы навсегда потеряли свой ключ и больше не сможете его восстановить.

**Comment by tundr1234** [comment]
I have a backup copy of the old key, when decrypting the open key chain
application, it writes encrypted data with a known private key not found

**Comment by tundr1234** [comment]
How can I find out which keys are used to enter the site ?

четверг, 31 августа 2023 г. пользователь Tundra Tundra ***@***.***>
написал:

**Comment by tundr1234** [comment]
I have a backup copy of the old key, when decrypting the open key chain
application, it writes encrypted data with a known private key not found

четверг, 31 августа 2023 г. пользователь Tundra Tundra ***@***.***>
написал:

**Comment by tundr1234** [comment]
Hello, how can I connect the old key if the new one was accidentally
deleted.


сб, 2 сент. 2023 г., 15:05 Tundra Tundra ***@***.***>:
