### ISSUE TITLE
USB CCID Support

### ISSUE THREAD

**Issue by roblabla** [open-keychain/open-keychain#1550]
Hello, I'm wondering if it'd be possible to use a card-reader USB CCID interface with open-keychain. The reason I ask is that I currently have a Yubikey NEO, but no NFC on my phone, so the only way to use the keys stored there from my phone would be through a USB OTG cable.

Any idea what would be necessary to support such a device ? It looks like it is possible to communicate with USB devices with the [USB Host Android API](http://developer.android.com/guide/topics/connectivity/usb/host.html). Would you be interested in supporting it ?

**Comment by Valodim** [comment]
Hi!

So first off, this is certainly possible technically. However, it is at least as much additional code complexity (probably more) as the NFC support we have right now. I also suspect that the actual use case is very rare: few people even consider the possibility to attach usb devices to their phone, and equally few people have a yubikey but no NFC reader.

So yes, this is a conceivable feature, but my gut feeling is that it's not worth it.

**Comment by dschuermann** [comment]
There is an OpenKeychain fork at https://github.com/nmikhailov/open-keychain/tree/otg that looks like it implements partial USB support.

@nmikhailov How is the progress on this? Do you have any questions?

**Comment by nmikhailov** [comment]
@dschuermann Hello. Yes I am trying to implement otg smartcard support(only for yubikey for now). So far it was pretty straightforward. Since you insist I will try to get back to it this week(I was focusing on other projects recently) and maybe file a PR or something.

**Comment by dschuermann** [comment]
@nmikhailov Sounds great, I am looking forward to see a PR :grin: If you have any technical questions, don't hesitate to ask here.

**Comment by dschuermann** [comment]
@nmikhailov Now that the Yubikey 4 is out that supports 4096 bit RSA but only USB, this feature becomes more interesting :)

**Comment by nmikhailov** [comment]
@dschuermann Yes, I have seen the announcement today and though that I should finally finish this. Sorry that I wasn't been able to finish it as promised. I indeed worked on it that week, but ended up loosing half of the time solving device specific otg issues, it could be very tricky and device-dependent.

**Comment by Valodim** [comment]
I would also encourage a work-in-progress PR for early feedback (I do that all the time) :+1:

**Comment by lbischof** [comment]
What's the status on this? Would this also work with a Nitrokey?

**Comment by nmikhailov** [comment]
1. I am planning to return to this soon.
2. Most likely no, at least in first iteration. But you can help test it.
If everything will be fine I might rollout more generic solution.

**Comment by jans23** [comment]
@nmikhailov great initiative. Do you want a free Nitrokey for testing purposes?

**Comment by dschuermann** [comment]
Since I suspect that Android will expand to other devices in 2016, this issue becomes more relevant. See for example http://www.jide.com/en/remixos

@jans23 We are also interested in free Nitrokeys :D If @nmikhailov creates a pull request, I need hardware to test this.

@nmikhailov If it only works properly on specific devices, I would propose that we use a whitelist of tested devices that work and check against this before allowing the user to use USB.

**Comment by nmikhailov** [comment]
I am sorry that I am so slow with this issue, don't worry I am still interested in it. BTW, I got device with NFC, so I can now test if haven't broken it in the process.

@jans23 that would be great, but I would suggest to postpone it until we have something done at least for yubikey.

**Comment by jans23** [comment]
@dschuermann No problem. :-)

**Comment by dschuermann** [comment]
done with https://github.com/open-keychain/open-keychain/pull/1824

**Comment by jans23** [comment]
Shouldn't this issue remain open as a "reminder" to tackle later?

**Comment by dschuermann** [comment]
@jans23 remaining improvements are now tracked here: https://github.com/open-keychain/open-keychain/issues/1833
