### ISSUE TITLE
Crash on import of key with many User IDs

### ISSUE THREAD

**Issue by ben-utzer** [open-keychain/open-keychain#1908]
This could be possibly related to the key, the key contains many IDs. OKC crashes on import from server or from file. I can import all other key fine. OKC also crashed on updating all keys and I added this key somehow before. I now removed it to test if updating all works and it does work now without a crash. But I can't import the key again into OKC. 

Key Fingerprint is: [B83559F2E5B4743316FB760A9C44492F5D25FD75](https://pgp.mit.edu/pks/lookup?search=0xB83559F2E5B4743316FB760A9C44492F5D25FD75&op=index)

**Comment by dschuermann** [comment]
Related https://github.com/open-keychain/open-keychain/issues/1714

**Comment by dschuermann** [comment]
This should be fixed in 4.3. Please try again. If there are still problems we can re-open this issue.

**Comment by ben-utzer** [comment]
The app is still crashing when importing the the key given above. When I search for the key online (rt at piratenpartei hyphen nrw dot de), when I tap the found key the app will crash, also wenn ich export the key with Enigmail on my laptop and then try to import if in Android.

Can you search for the key and try it yourself?

**Comment by dschuermann** [comment]
Thanks. This is a weird bug. stacktrace:

```
04-26 17:21:45.338  18646    25517             Keychain D  D  Keyserver search: https://hkps.pool.sks-keyservers.net/pks/lookup?op=index&options=mr&search=rt@piratenpartei.de using Proxy: DIRECT
04-26 17:21:45.347   3404     3404     InputMethodService  W  Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
04-26 17:21:47.403  18646    18646             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/-7186538637601407627/unified, proj=[verified])
04-26 17:21:47.408  18646    18646             Keychain D  D  Query: SELECT certs.verified FROM keys INNER JOIN user_packets ON (keys.master_key_id = user_packets.master_key_id AND user_packets.rank = 0) LEFT JOIN certs ON (keys.master_key_id = certs.master_key_id AND certs.verified = 1) WHERE (keys.rank = 0 AND keys.master_key_id = '-7186538637601407627') ORDER BY user_packets.user_id ASC
04-26 17:21:47.416  18646    25522             Keychain D  D  Multi-threaded key import starting
04-26 17:21:47.417  18646    25522             Keychain D  D  Send message by setProgress with progress=0, max=1
04-26 17:21:47.418  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_IMPORT, mParameters=[1], mIndent=0}
04-26 17:21:47.419  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IMPORT_KEYSERVER, mParameters=[hkps.pool.sks-keyservers.net], mIndent=1}
04-26 17:21:47.419  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=INFO, mType=MSG_IMPORT_FETCH_KEYSERVER, mParameters=[0x9c44492f5d25fd75], mIndent=2}
04-26 17:21:47.420  18646    25523             Keychain D  D  Keyserver get: https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0xb83559f2e5b4743316fb760a9c44492f5d25fd75 using Proxy: DIRECT
04-26 17:21:50.055  18646    25523             Keychain D  D  Found class: class org.bouncycastle.openpgp.PGPPublicKeyRing
04-26 17:21:50.055  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IMPORT_FETCH_KEYSERVER_OK, mParameters=null, mIndent=3}
04-26 17:21:50.055  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_IP, mParameters=[0x9c44492f5d25fd75], mIndent=0}
04-26 17:21:50.055  18646    25523             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/-7186538637601407627/unified, proj=[master_key_id, verified])
04-26 17:21:50.057  18646    25523             Keychain D  D  Query: SELECT keys.master_key_id, certs.verified FROM keys INNER JOIN user_packets ON (keys.master_key_id = user_packets.master_key_id AND user_packets.rank = 0) LEFT JOIN certs ON (keys.master_key_id = certs.master_key_id AND certs.verified = 1) WHERE (keys.rank = 0 AND keys.master_key_id = '-7186538637601407627') ORDER BY user_packets.user_id ASC
04-26 17:21:50.058  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_KC_PUBLIC, mParameters=[0x9c44492f5d25fd75], mIndent=1}
04-26 17:21:50.058  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_MASTER, mParameters=[0x9c44492f5d25fd75], mIndent=2}
04-26 17:21:50.134  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AG Reederei NRW (Queue AG Reederei NRW) <reederei@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.136  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Liquid Democracy (Queue Liquid Democracy) <liquid@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.138  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Datenschutz (Queue AK Datenschutz) <datenschutz@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.139  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Ausschreibung (Queue Ausschreibung) <ausschreibung@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.141  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Berti Comment (Queue-Comment Berti) <berti-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.142  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Essen Comment (Queue-Comment Essen) <essen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.151  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Gelsenkirchen (Queue Gelsenkirchen) <gelsenkirchen@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.151  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Hagen Comment (Queue-Comment Hagen) <hagen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.152  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Herne Comment (Queue-Comment Herne) <herne-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.153  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Kassenprüfer (Queue Kassenprüfer) <kassenpruefer@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.154  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Kleve Comment (Queue-Comment Kleve) <kleve-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.155  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Köln Comment (Queue-Comment Köln) <koeln-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.156  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Liquid Bounce (Queue Liquid Bounce) <liquid-bounce@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.157  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Lists Comment (Queue-Comment Lists) <lists-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.158  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Schatzmeister (Queue Schatzmeister) <schatzmeister@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.158  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Soest Comment (Queue-Comment Soest) <soest-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.159  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Spam Comment (Queue-Comment Spam) <spambox-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.160  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Vernetzung Kreise (Queue Vernetzung Kreise) <berti@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.161  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Wesel Comment (Queue-Comment Wesel) <wesel-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.163  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - WPS 3 Lektorat (Queue WPS 3 Lektorat) <wps.lektorat@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.164  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Landespolitik (Queue AK Landespolitik) <mitarbeit@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.165  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - E-Mail Comment (Queue-Comment E-Mail) <email-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.166  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - E-Mail Undelivered (Queue E-Mail Undelivered) <email@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.167  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Solingen Presse (Queue Solingen Presse) <presse@piratenpartei-solingen.de>], mIndent=3}
04-26 17:21:50.167  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - WPS 1 Eingang (Queue WPS 1 Eingang) <wahlpruefsteine@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.168  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Innenpolitik (Queue AK Innenpolitik) <innenpolitik@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.169  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Aachen Comment (Queue-Comment Aachen) <aachen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.170  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Bochum Comment (Queue-Comment Bochum) <bochum-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.171  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Borken Comment (Queue-Comment Borken) <borken-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.172  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Düren Comment (Queue-Comment Düren) <dueren-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.173  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Events Comment (Queue-Comment Events) <events-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.174  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Mumble Comment (Queue-Comment Mumble) <mumble-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.175  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Presse Comment (Queue-Comment Presse) <presse-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.176  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Recklinghausen (Queue Recklinghausen) <recklinghausen@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.177  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Schiedsgericht (Queue Schiedsgericht) <schiedsgericht@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.178  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - WPS 2 Bearbeitung (Queue WPS 2 Bearbeitung) <wps.edit@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.179  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - arndot Comment (Queue-Comment arndot) <arndot-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.180  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Lippe Comment (Queue-Comment Lippe) <vorstand-comment@piratenpartei-lippe.de>], mIndent=3}
04-26 17:21:50.181  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Solingen Kontakt (Queue Solingen Kontakt) <kontakt@piratenpartei-solingen.de>], mIndent=3}
04-26 17:21:50.182  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Verwaltung Piratenpartei NRW (Piratenpartei NRW RequestTracker) <verwaltung@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.183  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Drogenpolitik (Queue AK Drogenpolitik) <drogenpolitik@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.184  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Bottrop Comment (Queue-Comment Bottrop) <bottrop-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.185  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Herford Comment (Queue-Comment Herford) <herford-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.186  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Hosting Comment (Queue-Comment Hosting) <hosting-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.187  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Höxter Comment (Queue-Comment Höxter) <hoexter-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.188  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Kontakt Comment (Queue-Comment Kontakt) <kontakt-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.188  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Krefeld Comment (Queue-Comment Krefeld) <krefeld-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.189  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Umfrage Comment (Queue-Comment Umfrage) <umfrage-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.191  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Viersen Comment (Queue-Comment Viersen) <viersen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.192  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Schatzi - SAGE (Queue Schatzi - SAGE) <schatzmeister.sage@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.193  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Plakate & Werbemittel (Queue Plakate & Werbemittel) <berti@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.194  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Remscheid Kontakt (Queue Remscheid Kontakt) <kontakt@piratenpartei-remscheid.de>], mIndent=3}
04-26 17:21:50.195  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK KULNV Comment (Queue-Comment AK KULNV) <ak-kulnv-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.196  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Aktionen Comment (Queue-Comment Aktionen) <aktionen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.199  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Coesfeld Comment (Queue-Comment Coesfeld) <coesfeld-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.200  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Dortmund Comment (Queue-Comment Dortmund) <dortmund-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.201  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Duisburg Comment (Queue-Comment Duisburg) <duisburg-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.202  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Fraktion Kontakt (Queue Fraktion Kontakt) <fraktion-kontakt@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.203  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Krefeld Vorstand (Queue Krefeld Vorstand) <krefeld-vorstand@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.204  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Mettmann Comment (Queue-Comment Mettmann) <mettmann-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.205  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Minden-Lübbecke (Queue Minden-Lübbecke) <minden-luebbecke@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.206  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Mönchengladbach (Queue Mönchengladbach) <moenchengladbach@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.207  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Mülheim Comment (Queue-Comment Mülheim) <muelheim-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.208  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Münster Comment (Queue-Comment Münster) <muenster-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.209  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - RT-admin Comment (Queue-Comment RT-admin) <rt-admin-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.210  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Vorstand Comment (Queue-Comment Vorstand) <vorstand-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.211  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Webseite Comment (Queue-Comment Webseite) <webseite-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.214  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Jupi-presse Comment (Queue-Comment Jupi-presse) <jupi-presse-comment@jupis-nrw.de>], mIndent=3}
04-26 17:21:50.215  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Umlaufbeschlüsse (Queue Umlaufbeschlüsse) <umlaufbeschluss@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.216  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Antrag LPT Comment (Queue-Comment Antrag LPT) <antrag-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.217  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Blog Admins Comment (Queue-Comment Blog Admins) <blog-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.218  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Lippe Info Comment (Queue-Comment Lippe Info) <info-comment@piratenpartei-lippe.de>], mIndent=3}
04-26 17:21:50.219  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Kultur Comment (Queue-Comment AK Kultur) <ak-kultur-comment@Piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.220  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Antragskommission (Queue Antragskommission) <antragskommission@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.220  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Bielefeld Comment (Queue-Comment Bielefeld) <bielefeld-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.221  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Dortmund-Vorstand (Queue Dortmund-Vorstand) <dortmund-vorstand@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.222  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Einladung Comment (Queue-Comment Einladung) <einladung-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.223  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Heinsberg Comment (Queue-Comment Heinsberg) <heinsberg-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.224  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Märkischer Kreis (Queue Märkischer Kreis) <maerkischer-kreis@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.224  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Paderborn Comment (Queue-Comment Paderborn) <paderborn-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.225  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Remscheid Comment (Queue-Comment Remscheid) <remscheid-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.226  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Rhein-Kreis Neuss (Queue Rhein-Kreis Neuss) <rhein-kreis-neuss@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.227  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Sitzungskommission (Queue Sitzungskommission) <vorstandsantrag@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.228  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Steinfurt Comment (Queue-Comment Steinfurt) <steinfurt-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.229  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Vernetzung Bund/Länder (Queue Vernetzung Bund/Länder) <berti@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.230  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Warendorf Comment (Queue-Comment Warendorf) <warendorf-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.231  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Wuppertal Comment (Queue-Comment Wuppertal) <wuppertal-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.232  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Zwitscher Comment (Queue-Comment Zwitscher) <zwitscher-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.232  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Technik Comment (Queue-Comment Technik) <technik-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.233  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Direktkandidaten (Queue Direktkandidaten) <direktkandidatenwahl@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.234  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Verwaltung Mitglieder (Queue Verwaltung Mitglieder) <verwaltung@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.235  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - gensec Comment (Queue-Comment gensec) <generalsekretaer-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.236  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Verwaltung Piratenpartei NRW (Piratenpartei NRW RequestTracker) <verwaltung-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.237  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - OWL-Kontakt Comment (Queue-Comment OWL-Kontakt) <kontakt-comment@piratenpartei-owl.de>], mIndent=3}
04-26 17:21:50.237  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Bildung Comment (Queue-Comment AK Bildung) <ak-bildung-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.238  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Digitales Aachen (Queue AK Digitales Aachen) <digitales-aachen@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.239  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - AK Kommunalfinanzen (Queue AK Kommunalfinanzen) <kommunalfinanzen@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.240  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Bestellung Comment (Queue-Comment Bestellung) <bestellung-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.242  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - Euskirchen Comment (Queue-Comment Euskirchen) <euskirchen-comment@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.243  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_TOO_MANY, mParameters=[Piratenpartei NRW - FullerensTestQueue (Queue FullerensTestQueue) <FullerensTestQueue@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.246  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_CERT_DUP, mParameters=[Piratenpartei NRW - FullerensTestQueue (Queue FullerensTestQueue) <FullerensTestQueue@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.248  18646    25523             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_KC_UID_CERT_DUP, mParameters=[Piratenpartei NRW - FullerensTestQueue (Queue FullerensTestQueue) <FullerensTestQueue@piratenpartei-nrw.de>], mIndent=3}
04-26 17:21:50.261  18646    25522             Keychain D  E  A key could not be imported during multi-threaded import
04-26 17:21:50.261  18646    25522             Keychain D  E  java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to read from field 'org.bouncycastle.bcpg.PublicKeyPacket org.bouncycastle.openpgp.PGPPublicKey.publicPk' on a null object reference
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.FutureTask.report(FutureTask.java:94)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.FutureTask.get(FutureTask.java:164)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:508)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:456)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:83)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:151)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.lang.Thread.run(Thread.java:761)
04-26 17:21:50.261  18646    25522             Keychain D  E  Caused by: java.lang.NullPointerException: Attempt to read from field 'org.bouncycastle.bcpg.PublicKeyPacket org.bouncycastle.openpgp.PGPPublicKey.publicPk' on a null object reference
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.bouncycastle.openpgp.PGPPublicKey.<init>(PGPPublicKey.java:150)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.bouncycastle.openpgp.PGPPublicKey.removeCert(PGPPublicKey.java:910)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.bouncycastle.openpgp.PGPPublicKey.removeCertification(PGPPublicKey.java:870)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:586)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:292)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.provider.KeyWritableRepository.savePublicKeyRing(KeyWritableRepository.java:814)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:325)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:83)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:497)
04-26 17:21:50.261  18646    25522             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:485)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-26 17:21:50.261  18646    25522             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-26 17:21:50.261  18646    25522             Keychain D  E  ... 1 more
--------- beginning of crash04-26 17:21:50.263  18646    25522         AndroidRuntime  E  FATAL EXCEPTION: Thread-27
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 18646
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to read from field 'org.bouncycastle.bcpg.PublicKeyPacket org.bouncycastle.openpgp.PGPPublicKey.publicPk' on a null object reference
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:517)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:456)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:83)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:151)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:761)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to read from field 'org.bouncycastle.bcpg.PublicKeyPacket org.bouncycastle.openpgp.PGPPublicKey.publicPk' on a null object reference
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.FutureTask.report(FutureTask.java:94)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.FutureTask.get(FutureTask.java:164)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:508)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  ... 4 more
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  Caused by: java.lang.NullPointerException: Attempt to read from field 'org.bouncycastle.bcpg.PublicKeyPacket org.bouncycastle.openpgp.PGPPublicKey.publicPk' on a null object reference
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.bouncycastle.openpgp.PGPPublicKey.<init>(PGPPublicKey.java:150)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.bouncycastle.openpgp.PGPPublicKey.removeCert(PGPPublicKey.java:910)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.bouncycastle.openpgp.PGPPublicKey.removeCertification(PGPPublicKey.java:870)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:586)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:292)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.provider.KeyWritableRepository.savePublicKeyRing(KeyWritableRepository.java:814)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:325)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:83)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:497)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:485)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-26 17:21:50.263  18646    25522         AndroidRuntime  E  ... 1 more
```

**Comment by dschuermann** [comment]
Looks like it crashes when trying to remove a duplicate certificate.

On a related note: We currently stop importing after 100 User IDs. I think the limit is a little bit low. Maybe we can increase this to 1000? @Valodim what do you think?

**Comment by ben-utzer** [comment]
> Looks like it crashes when trying to remove a duplicate certificate.

Certificate as in key or as in signature of a key. Sorry I am not that firm with the log output above.

**Comment by dschuermann** [comment]
@ben-utzer It's okay, this was more a comment for me or @Valodim 😬 

There are duplicate User ID certificates attached to this key, so OpenKeychain tries to remove one, this edge-case leads to a crash.
