### ISSUE TITLE
After upgrade to 5.11, crash alot

### ISSUE THREAD

**Issue by johnwmail** [open-keychain/open-keychain#2352]
## Steps to Reproduce (for bugs)

1.click refresh all the keys (I have 5)
2.then open keychain crash
No problem before update to 5.11/5.12
3.
4.

## Your Environment

* Android Version: 5.xx
* Device Model: note3
* OpenKeychain Version: 5.12
* From Google Play or F-Droid?: Google play

**Comment by dschuermann** [comment]
We just released 5.1.2. Please try this version.

**Comment by johnwmail** [comment]
Sorry to say that.
Yes, I already installed 5.1.2, and still have the problem. 
Please help, thank you.

**Comment by dschuermann** [comment]
Please report the crash to Google Play when it happens. Then we can see the details of the bug.

**Comment by johnwmail** [comment]
Version 51200

**Comment by johnwmail** [comment]
Report to Google play?

How?

**Comment by Valodim** [comment]
The reports might be sent automatically, but we're not seeing any so far. We'll keep watch.

This might be related to the keys in your key list. Does it also crash when you update any key individually? (small loop-arrow icon on top right in key view)

**Comment by johnwmail** [comment]
Yes,it crash , when I refresh the key, no matter which one(individually), or all
I want to export the keylist for someone testing, but do not know how to do that on keychain, anyway, my key
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x182C97DBCF2C80AC

**Comment by johnwmail** [comment]
Click the search key function also crash.
No matter search what

**Comment by johnwmail** [comment]
Upgrade to 5.1.3 51300 , still have the problem

**Comment by bazio101** [comment]
Same behavior when trying to search for a key on server.
Android 4.2.2
Version 5.1.3 f-droid
Don't use PlayStore to report it.
This is log entry:


**AndroidRuntime**
FATAL EXCEPTION: ModernAsyncTask #2
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.ExceptionInInitializerError
	at org.sufficientlysecure.keychain.keyimport.CloudSearch.search(CloudSearch.java:46)
	at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListCloudLoader.queryServer(ImportKeysListCloudLoader.java:141)
	at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:80)
	at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:39)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 3 more
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 4:
(?<uid>uid:(?<uidID>[^:
]*)(?::(?<uidCreate>[0-9]*)(?::(?<uidExpire>[0-9]*)(?::(?<uidFlags>((?=(r(?!(.?r))|d(?!(.?d))|e(?!(.?e))))[rde]){0,3}))?)?)?
)
    ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:407)
	at java.util.regex.Pattern.<init>(Pattern.java:390)
	at java.util.regex.Pattern.compile(Pattern.java:374)
	at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.<clinit>(HkpKeyserverClient.java:84)
	... 12 more


**InputDispatcher**
channel '42ae2be8 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!


**AndroidRuntime**
FATAL EXCEPTION: Thread-2083
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:573)
	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:513)
	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:87)
	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:148)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
	at java.util.concurrent.FutureTask.get(FutureTask.java:160)
	at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:564)
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at org.sufficientlysecure.keychain.operations.ImportOperation.fetchKeyFromKeyserver(ImportOperation.java:388)
	at org.sufficientlysecure.keychain.operations.ImportOperation.fetchKeyFromInternet(ImportOperation.java:348)
	at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:195)
	at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:87)
	at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:553)
	at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:541)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	... 1 more
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 4:
(?<uid>uid:(?<uidID>[^:
]*)(?::(?<uidCreate>[0-9]*)(?::(?<uidExpire>[0-9]*)(?::(?<uidFlags>((?=(r(?!(.?r))|d(?!(.?d))|e(?!(.?e))))[rde]){0,3}))?)?)?
)
    ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:407)
	at java.util.regex.Pattern.<init>(Pattern.java:390)
	at java.util.regex.Pattern.compile(Pattern.java:374)
	at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.<clinit>(HkpKeyserverClient.java:84)
	... 12 more

First and second entry are about search key and third on update keys.
Hope it helps

**Comment by Valodim** [comment]
Aahh, that stack trace actually helps a lot! I wasn't aware you were using such an ancient version of Android. We'll get it fixed :+1:

**Comment by dschuermann** [comment]
Please try OpenKeychain 5.1.4 and report back

**Comment by johnwmail** [comment]
I can confirm, 5.1.4 fixed the problem,thanks.
