### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by DominikGolle** [open-keychain/open-keychain#2456]
I probably missed something obvious, but Openkeychain gets a certificate error when trying to update keys or searching for keys.

## Expected Behavior
When searching for keys or updating keys, app should contact keyservers, when there is an internet connection.

## Current Behavior
Despite wifi or 4G connection, I get a network/certificate error (see attached file) when trying to update or search for keys.

When seaching for keys by name (without entering an email address or more specifically an @-Symbol), keybase.io is queried correctly. Once I enter an emailaddress, I immediatly get a network error.

## Steps to Reproduce (for bugs)
1. Fresh install Openkeychain
2. Whitelist Openkeychain in AFWall+ (if necessary)
3. Search for a key via an email address

## Your Environment
* Android Version: lineage OS 15.1 (Android 8.1.0)
* Device Model: Fairphone 2
* OpenKeychain Version: 5.2
* From Google Play or F-Droid?: Google Play
 
[openkeychain_log.txt](https://github.com/open-keychain/open-keychain/files/3115642/openkeychain_log.txt)

**Comment by TheBestF22** [comment]
Verified this with **DEFAULT Settings** on Latest Google Play (Release Version).

@dschuermann @Valodim  -->  This is **Kind of URGENT** I'd say...  (Affects EVERY install with the Default KeyServers)
I've even narrowed the Problem Down:
 - Apparently, **[keyserver.ubuntu.com](https://keyserver.ubuntu.com/)** Changed Their Certificate and the APP's own **HARDCODED** "Certificate Pinning" (as called in Source Code Method) is feeding the Wrong Certificate to the Connection - making it fail.
  https://github.com/open-keychain/open-keychain/blob/0a001e4cf676f349c31aa0ae60e93c52aaf08e79/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java#L105    
  
  
  
### **TEMPORARY FIX/WORKAROUND**
@DominikGolle 
 - Move the **keyserver.ubuntu.com** Server down (to the bottom) over on the APP's "Options" Menu.    
  
  
  C Ya L8r then!.    **;P**

**Comment by TheBestF22** [comment]
@DominikGolle  
  Now that You know what's the Problem, I'd suggest You to Change the **issue**'s **"Title"** (if You can).
  (a Change in the Site's *Certificate* and even its *Certificate Issuer*)

NOTE:
 - The *"**TEMPORARY WORKAROUND**"* I suggested is just that; it is **NOT** a Real Solution - the **issue** is **NOT** Solved!.  
  
  Bye then.

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/adcb39b5c831f8a7cb9ef6a01ddeaae2e202e878 and released in 5.3

**Comment by algo7** [comment]
Apparently, this still occurs on Asus ROG 3 running Android 10.

**Comment by LordPong** [comment]
Problem seems to be fixed in App version 5.6.2 (56200)
