### ISSUE TITLE
ECDSA signatures interpreted as signed integers

### ISSUE THREAD

**Issue by mrmekon** [open-keychain/open-keychain#2497]
As reported on the mailing list:

I'm trying to understand why OpenKeychain is crashing frequently when generating P-256 signatures with smartcard tokens.  After a brief investigation, it looks like it's throwing an IllegalArgumentException when converting the smartcard's response into an MPInteger object.

I investigated on the public git repo, commit b35292f1078968c3121a2fb6f45daab1b27fb9fe.

It's reaching PGPSignatureGenerator::generate(), calling PGPUtil.dsaSigToMpi(), calling MPInteger() on the unwrapped 'r' and 's' values, and throwing an exception if the high bit is set (interpreting it as a sign bit).

This differs from GnuPG, which interprets 'r' and 's' as unsigned integers (GnuPG's do_sign() in g10/sign.c) and accepts any of these signatures.

I found an old issue on the OpenKeychain issue tracker:
https://github.com/open-keychain/open-keychain/issues/2108

As the comments there state, a token should only pad short 'r' and 's' values up to the key length.  Further padding to encode them as unsigned integers is up to the receiving application, if necessary.

I notice that when using a local key without a token, 'r' and 's' appear to be padded out with an extra 0 byte if the highest bit is set.  I think that should always happen, but that step is being skipped for smartcard tokens.

An annotated example, horribly formatted:

-----
#### OpenKeychain makes a PSO (digital signature) request to token:

`NfcTransport: nfc out: 002a9e9a000040cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e0000`

#### Token responds with concatenated r|s|APDU_SW

`NfcTransport: nfc  in: c143ffc54d4e0fe07a338a002e1e7ed3383cd0ca66e94e1a427c38297ff59fdcb1fbdd197f028691899c1024017c67b1bd107c7fc9c630359f8cb7923a4b99c39000`

#### SecurityTokenPsoSignTokenOp.java wraps it in an ASN.1 structure:

```
RAW SIG: C143FFC54D4E0FE07A338A002E1E7ED3383CD0CA66E94E1A427C38297FF59FDCB1FBDD197F028691899C1024017C67B1BD107C7FC9C630359F8CB7923A4B99C3
ASN1 SIG: 30440220C143FFC54D4E0FE07A338A002E1E7ED3383CD0CA66E94E1A427C38297FF59FDC0220B1FBDD197F028691899C1024017C67B1BD107C7FC9C630359F8CB7923A4B99C3
```

#### dsaSigToMpi() unwraps the ASN.1 structure:

```
i1: sign: -1 / data: c143ffc54d4e0fe07a338a002e1e7ed3383cd0ca66e94e1a427c38297ff59fdc
i2: sign: -1 / data: b1fbdd197f028691899c1024017c67b1bd107c7fc9c630359f8cb7923a4b99c3
```

#### MPInteger() rejects signed integers

```
FATAL EXCEPTION: AsyncTask #8
Process: org.sufficientlysecure.keychain, PID: 13579
java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: value must not be null, or negative
       at org.bouncycastle.bcpg.MPInteger.<init>(MPInteger.java:31)
       at org.bouncycastle.openpgp.PGPUtil.dsaSigToMpi(PGPUtil.java:77)
       at org.bouncycastle.openpgp.PGPSignatureGenerator.generate(PGPSignatureGenerator.java:277)
       at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.executeInternal(PgpSignEncryptOperation.java:573)
       at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.execute(PgpSignEncryptOperation.java:156)
       at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:92)
       at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:52)
       at org.sufficientlysecure.keychain.service.KeychainServiceTask$1.doInBackground(KeychainServiceTask.java:137)
       at org.sufficientlysecure.keychain.service.KeychainServiceTask$1.doInBackground(KeychainServiceTask.java:83)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       ... 4 more
   Force finishing activity org.sufficientlysecure.keychain/.ui.EncryptFilesActivity
```
-----

**Comment by dschuermann** [comment]
Should be fixed in 5.7

**Comment by mochaaP** [comment]
Still crashing in 5.7.4 (F-Droid version).

Using Yubikey 5 NFC with P-256 with two identities on Android 11.

Log: https://del.dog/wexitettil

**Comment by luketeam5** [comment]
Hello,
I was directed here by the [FairEmail](https://email.faircode.eu/) developer.

I am experiencing an issue with an OpenKeychain generated key that was created using a hardware key (Yubikey 5 NFC). Whenever I try to use this key for signing or encrypting operations within the FairEmail application, I receive the error message "OpenPgp error 0: value must not be null or negative." 

I have attached a screenshot of the error for reference: ![b4du7Lug](https://github.com/open-keychain/open-keychain/assets/40070133/e9110091-5ef1-489f-ad5f-76534749e434)

I apologize for not being able to provide error logs. Unfortunately, I am uncertain of what specific information might be helpful in this situation or how to obtain the logs.

---
* EvolutionX - 8.2 (Tikoy) | sweet | OFFICIAL
* Android Version: Android 14
* Device Model: Xiaomi M2110K6G
* OpenKeychain Version: 6.0.0 (60000)
* From Google Play or F-Droid?: F-Droid (thru Neo Store)

**Comment by mochaaP** [comment]
This is finally fixed, TYSM!
