### ISSUE TITLE
Bugs in version 6.0.0 from F-Droid

### ISSUE THREAD

**Issue by rafaelazvdo** [open-keychain/open-keychain#2880]
Bug 1: In light mode, when backing up a key, the password appears in white text against a white background.

![Screenshot_20240212_011501_OpenKeychain.jpg](https://github.com/open-keychain/open-keychain/assets/122113441/62bedf90-347c-4338-8746-d491296296b2)

Bug 2: When trying to decrypt pgp/gpg files and texts, encrypted with a password, the application displays the decryption screen and the text "reading data" but nothing else happens.  File and text decryption using the key pair occurs normally without errors.

**Comment by rafaelazvdo** [comment]
Bug 2 also occurs when trying to restore a key that has been backed up by the application, as it is a pgp file encrypted with a password.

**Comment by basilgello** [comment]
OkcAgent integration also broken: namely, the am broadcast is passed correctly, and the passphrase dialog is reported to display (from logcat) but in fact no dialog window appears.

**Comment by rafaelazvdo** [comment]
> OkcAgent integration also broken: namely, the am broadcast is passed correctly, and the passphrase dialog is reported to display (from logcat) but in fact no dialog window appears.

It's not working with K9-mail, the email application closes by itself when you type anything in the recipient, but with FairEmail, it appears to be working without any problems.

**Comment by basilgello** [comment]
Light and dark mode toggle is also switched vice versa

**Comment by rafaelazvdo** [comment]
> Light and dark mode toggle is also switched vice versa

This problem appeared in version 5.8.0, when the automatic theme option was implemented.

**Comment by basilgello** [comment]
#2883

**Comment by us4r01d** [comment]
Both Bugs also happend to me

**Comment by Valodim** [comment]
bug 2 is fixed. I wasn't able to reproduce bug 2 though :thinking:

**Comment by rafaelazvdo** [comment]
> bug 2 is fixed. I wasn't able to reproduce bug 2 though :thinking: 

Bug 2 occurs when trying to decrypt pgp/gpg files that were encrypted using this option marked in the screenshot "Encrypt with password", regardless of whether the other options below are checked or not, it is not limited only to files encrypted by Openkeychain, but it This bug also presents when trying to decrypt pgp files with a password, without an associated key pair encrypted by other software, such as Kleopatra.

![Screenshot_20240216_084212_OpenKeychain.jpg](https://github.com/open-keychain/open-keychain/assets/122113441/b414f110-c983-4895-9390-b367824ba93f)

**Comment by basilgello** [comment]
6.0.1 fixed all passphrase dialog invocations. I checked your scenario with local build of 6.0.1 and was able to encrypt and decrypt file with password without problems.

**Comment by Valodim** [comment]
sorry, I meant bug 1 was the one I couldn't reproduce. which makes more sense, since bug 2 is fixed :)

**Comment by rafaelazvdo** [comment]
> sorry, I meant bug 1 was the one I couldn't reproduce. which makes more sense, since bug 2 is fixed :)

Bug 1 only occurs when the system is in dark mode, but only Openkeychain is configured to display light mode by changing the theme setting within the application itself.

With Android in light mode, both manual and automatic configuration of the Openkeichain theme, bug 1 does not occur.

**Comment by rafaelazvdo** [comment]
> sorry, I meant bug 1 was the one I couldn't reproduce. which makes more sense, since bug 2 is fixed :)

@Valodim this bug is still present in version 6.0.2, to reproduce it Android must be in dark mode and Openkeychain must be configured to display light mode, when accessing the menu to backup the key, the backup password is displayed in an almost 100% white tone on a white background.
